title: "Self-Illusion: A Study on Cognition of Role-Playing in Immersive Virtual Environments"
description: Sheng Li, Xiang Gu, Kangrui Yi, Yanlin Yang, Guoping Wang, and Dinesh Manocha
theme: jekyll-theme-slate


